# Generated by Django 2.0.9 on 2019-01-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0123_auto_20190115_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Popis trasy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Označit trasa jako oblibené'),
        ),
    ]
